#!/usr/bin/env python3
"""Generate every redirect artefact from one source: redirect-map.csv.

Run from the redirects/ folder:  python3 build-redirects.py [site_dir]

Writes _redirects, htaccess-snippet.txt, nginx-snippet.conf and
_redirects-extensionless from the CSV, then verifies every target page and
#anchor against the built site so a stale row cannot ship silently.

Keeping one generator means the four server formats can never drift apart -
edit the CSV, re-run this, commit all five files together.
"""
import csv, io, os, re, sys

HOST = 'https://goracfit.com'
SITE = sys.argv[1] if len(sys.argv) > 1 else '..'
HERE = os.path.dirname(os.path.abspath(__file__)) or '.'

# ---------------------------------------------------------------- WordPress
# Not in the sitemap, so not in the CSV - but WordPress published all of these
# and crawlers and old inbound links still request them. Left out, every one is
# a 404 after launch. Patterns, so they stay in the generator, not the sheet.
WP_PATTERNS = [
    # (label, netlify_from, netlify_to, apache_rule, nginx_rule)
    ('main feed', '/feed/*', '/', 'RewriteRule ^feed/?$ / [R=301,L]',
     'location ^~ /feed { return 301 /; }'),
    ('comment + per-page feeds', '/*/feed/*', '/', 'RewriteRule ^(.+)/feed/?$ /$1 [R=301,L]',
     'location ~ ^/(.+)/feed/?$ { return 301 /$1; }'),
    ('category archives', '/category/*', '/', 'RewriteRule ^category/(.*)$ / [R=301,L]',
     'location ^~ /category/ { return 301 /; }'),
    ('tag archives', '/tag/*', '/', 'RewriteRule ^tag/(.*)$ / [R=301,L]',
     'location ^~ /tag/ { return 301 /; }'),
    ('author archives', '/author/*', '/about.html#team',
     'RewriteRule ^author/(.*)$ /about.html#team [R=301,L,NE]',
     'location ^~ /author/ { return 301 /about.html#team; }'),
    ('date archives', '/20*/*', '/', 'RewriteRule ^[0-9]{4}(/[0-9]{2})*/?$ / [R=301,L]',
     'location ~ ^/[0-9]{4}(/[0-9]{2})*/?$ { return 301 /; }'),
    ('admin + login', '/wp-admin/*', '/', 'RewriteRule ^wp-admin(/.*)?$ / [R=301,L]',
     'location ^~ /wp-admin { return 301 /; }'),
    ('login', '/wp-login.php', '/', 'RewriteRule ^wp-login\\.php$ / [R=301,L]',
     'location = /wp-login.php { return 301 /; }'),
    ('json api', '/wp-json/*', '/', 'RewriteRule ^wp-json(/.*)?$ / [R=301,L]',
     'location ^~ /wp-json { return 301 /; }'),
    ('xmlrpc', '/xmlrpc.php', '/', 'RewriteRule ^xmlrpc\\.php$ / [R=301,L]',
     'location = /xmlrpc.php { return 301 /; }'),
]


def load():
    rows = list(csv.DictReader(io.open(os.path.join(HERE, 'redirect-map.csv'), encoding='utf-8')))
    out = []
    for r in rows:
        if (r.get('status') or '').strip().lower() in ('', 'none', '-'):
            continue                      # documented as "no redirect"
        old = r['old_url'].replace(HOST, '') or '/'
        new = r['new_url'].replace(HOST, '') or '/'
        if old.rstrip('/') == new.rstrip('/').replace('.html', ''):
            pass                          # still emit; the host may not do pretty URLs
        out.append((old, new, r['status'], r['confidence']))
    return out


def strip_ext(target):
    page, _, frag = target.partition('#')
    if page.endswith('.html'):
        page = page[:-5]
        if page == '/index':
            page = '/'
    return page + (('#' + frag) if frag else '')


def write_netlify(rows, path, extensionless=False):
    L = ['# RacFit 301 map - old WordPress URLs to the rebuilt static site',
         '# GENERATED by build-redirects.py from redirect-map.csv - do not hand-edit.',
         '']
    if extensionless:
        L += ['# Extensionless variant. Use this one on a host that serves /about for',
              '# about.html and 301s the .html form, so old URLs land in a single hop',
              '# instead of chaining through /about.html.', '']
    w = max(len(o) for o, *_ in rows) + 2
    for old, new, status, conf in rows:
        t = strip_ext(new) if extensionless else new
        L.append('%-*s %-45s %s%s' % (w, old, t, status, '' if conf == 'clear' else '   # confirm'))
    L += ['', '# --- WordPress platform paths (not in the sitemap, still requested) ---']
    for label, frm, to, _, _n in WP_PATTERNS:
        t = strip_ext(to) if extensionless else to
        L.append('%-*s %-45s 301   # %s' % (w, frm, t, label))
    io.open(path, 'w', encoding='utf-8').write('\n'.join(L) + '\n')


def write_apache(rows, path):
    L = ['# RacFit 301 map - paste above any existing rewrite rules.',
         '# GENERATED by build-redirects.py from redirect-map.csv - do not hand-edit.',
         '<IfModule mod_rewrite.c>', '  RewriteEngine On', '',
         '  # canonical host: the apex. www 301s here.',
         '  RewriteCond %{HTTP_HOST} ^www\\. [NC]',
         '  RewriteRule ^(.*)$ https://goracfit.com/$1 [R=301,L]', '']
    for old, new, _s, conf in rows:
        pat = '^' + old.strip('/').replace('.', '\\.') + '/?$'
        L.append('  RewriteRule %s %s [R=301,L,NE]%s' % (pat, new, '' if conf == 'clear' else '   # confirm'))
    L += ['', '  # --- WordPress platform paths (not in the sitemap, still requested) ---']
    for label, _f, _t, rule, _n in WP_PATTERNS:
        L.append('  %s   # %s' % (rule, label))
    L += ['', '  # WordPress ugly permalinks: /?p=123 and /?page_id=12',
          '  RewriteCond %{QUERY_STRING} ^(p|page_id)=[0-9]+$',
          '  RewriteRule ^$ / [R=301,L]', '', '</IfModule>']
    io.open(path, 'w', encoding='utf-8').write('\n'.join(L) + '\n')


def write_nginx(rows, path):
    L = ['# RacFit 301 map - place inside the server block.',
         '# GENERATED by build-redirects.py from redirect-map.csv - do not hand-edit.', '']
    for old, new, _s, conf in rows:
        L.append('location = %s { return 301 %s; }%s' % (old, new, '' if conf == 'clear' else '   # confirm'))
    L += ['', '# --- WordPress platform paths (not in the sitemap, still requested) ---']
    for label, _f, _t, _a, rule in WP_PATTERNS:
        L.append('%s   # %s' % (rule, label))
    io.open(path, 'w', encoding='utf-8').write('\n'.join(L) + '\n')


def verify(rows):
    ids, problems = {}, []
    for f in os.listdir(SITE):
        if f.endswith('.html'):
            ids[f] = set(re.findall(r'id="([^"]+)"', io.open(os.path.join(SITE, f), encoding='utf-8').read()))
    for old, new, _s, _c in rows:
        page, _, frag = new.lstrip('/').partition('#')
        page = page or 'index.html'
        if page not in ids:
            problems.append('%s -> %s  PAGE MISSING' % (old, new))
        elif frag and frag not in ids[page]:
            problems.append('%s -> %s  ANCHOR MISSING' % (old, new))
    return ids, problems


if __name__ == '__main__':
    rows = load()
    write_netlify(rows, os.path.join(HERE, '_redirects'))
    write_netlify(rows, os.path.join(HERE, '_redirects-extensionless'), extensionless=True)
    write_apache(rows, os.path.join(HERE, 'htaccess-snippet.txt'))
    write_nginx(rows, os.path.join(HERE, 'nginx-snippet.conf'))
    ids, problems = verify(rows)
    print('%d redirect rows written to 4 server formats' % len(rows))
    print('%d WordPress platform patterns appended' % len(WP_PATTERNS))
    print('%d pages in the build' % len(ids))
    if problems:
        print('\nBROKEN TARGETS (%d):' % len(problems))
        for p in problems:
            print('  ' + p)
        raise SystemExit(1)
    print('every target page and anchor verified against the build')
